os: linux
dist: bionic

cache:
    - npm
    - yarn

language: node_js

node_js:
    - lts/*

install:
    - yarn

jobs:
    include:
        - stage: Test
          script:
              - yarn test
        - stage: Deploy # Windows
          if: tag IS present
          os: windows
          env:
              - YARN_GPG=no
          script:
              - yarn electron-forge publish
        - # MacOSz
          if: tag IS present
          os: osx
          osx_image: xcode12
          script:
              - yarn electron-forge publish
        - # Linux
          if: tag IS present
          addons:
              apt:
                  packages:
                      - dpkg
                      - fakeroot
                      - rpm
                      - snapcraft
          script:
              - yarn electron-forge publish
          deploy:
              provider: snap
              cleanup: false
              edge: true
