os: linux
dist: bionic

cache:
    - npm
    - yarn

language: node_js

node_js:
    - lts/*

install:
    - yarn

jobs:
    include:
        - stage: Test
          script:
              - yarn test
        - stage: Deploy # Windows
          if: tag IS present
          os: windows
          before_install:
              - export GRADLE_OPTS=-Dorg.gradle.daemon=false
          script:
              - yarn electron-forge publish
        - # MacOS
          if: tag IS present
          os: osx
          osx_image: xcode12
          script:
              - yarn electron-forge publish
        - # Linux
          if: tag IS present
          addons:
              apt:
                  packages:
                      - dpkg
                      - fakeroot
                      - rpm
                      - snapcraft
          install:
              - flatpak --user install gnome org.freedesktop.Sdk/x86_64/1.4
              - yarn
          script:
              - yarn electron-forge publish
          deploy:
              provider: snap
              cleanup: false
              edge: true
